### ISSUE TITLE
v0.4.1 can't seem to login

### ISSUE THREAD

**Issue by seb2010** [DrozmotiX/ioBroker.tado#561] opened 2022-11-27 15:04 UTC
I tried v0.4.1 and it does not get past the log-message "GetMe result". It occurs everytime I try to send a command. No data is beeing updated:
<html>
<body>

tado.0 | 2022-11-27 15:58:22.341 | info | Initialisation finished, connected to Tado cloud service refreshing every 30 seconds
-- | -- | -- | --
tado.0 | 2022-11-27 15:58:22.308 | debug | GetMe result: "\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0000\u0000�S�n�@\u00......................."
tado.0 | 2022-11-27 15:58:22.104 | info | Connected to Tado cloud, initialyzing...
tado.0 | 2022-11-27 15:58:21.634 | debug | Internet connection detected. Everything fine!
tado.0 | 2022-11-27 15:58:21.514 | info | Started with JSON-Explorer version 0.1.9
tado.0 | 2022-11-27 15:58:21.465 | info | starting. Version 0.4.1 in /opt/iobroker/node_modules/iobroker.tado, node: v16.18.1, js-controller: 4.0.23

</body>
</html>
There is no json-output in debug-mode listing all the api-results following. Hence the adapter does not sync API to object read/Write.

Reverting back to 0.4.0 solves the issue.

**Comment by HGlab01** [comment] 2022-11-27 15:39
I did two major lib updates. As I cannot reproduce the issue, can you please test following three versions and let me know if one of those are working

During the startup of the adapter you will find an additional log-line with
`axios version is x.x.x and simple-oauth2 version is x.x.x`
This line will display different versions for the three installs. The adapter version number itself did not change!

Install 1
DrozmotiX/ioBroker.tado#c56acce9b7f20f566e116d5b7bb15de6733a4d13

Install 2
DrozmotiX/ioBroker.tado#7bdebac4ee9c228843c6b1f29818fb716935c567

Install 3
DrozmotiX/ioBroker.tado#ac2e935c17c401909b1c47ca07a070454c1b4724

Installs work in Expert mode with the "cat" in the Adapter tab.
![image](https://user-images.githubusercontent.com/54232526/204143869-d859a459-3a3b-4d7c-b1a1-109786736eed.png)

**Comment by seb2010** [comment] 2022-11-27 15:47
axios version is 0.27.2 and simple-oauth2 version is 5.0.0
works

**Comment by seb2010** [comment] 2022-11-27 15:49
aios version is 1.2.0 and simple-oauth2 version is 5.0.0
does not work


</body>
</html>
axios version is 1.2.0 and simple-oauth2 version is 5.0.0
--



</body>
</html>

**Comment by seb2010** [comment] 2022-11-27 15:50
axios version is 1.2.0 and simple-oauth2 version is 4.3.0
does not work

**Comment by HGlab01** [comment] 2022-11-27 15:53
Thanks a lot!
I guess this version works as well (axios 1.1.3 and outh2 in 5.0.0)
DrozmotiX/ioBroker.tado#317796207d02ea797c30b056ce4fcf71d92c10a2

**Comment by seb2010** [comment] 2022-11-27 15:54
yes you are right, this one work as well
<html>
<body>


axios version is 1.1.3 and simple-oauth2 version is 5.0.0
--



</body>
</html>

**Comment by HGlab01** [comment] 2022-11-27 15:58
Thanks for your quick support!
Will create a new version in the next hours

**Comment by HGlab01** [comment] 2022-11-27 16:13
fixed in https://github.com/DrozmotiX/ioBroker.tado/releases/tag/v0.4.2

**Closed** 2022-11-28 12:45 UTC
Labels: bug
